version: "3"
services:
  redis:
    build:
      context: ./redis
    expose:
      - "6379:6379"
    networks:
      - backend
      - frontend
    depends_on:
      - vote

  db:
    build:
      context: ./postgre
    expose:
      - "5432:5432"
    volumes:
      - votes:/var/lib/postgresql/data
    networks:
      - backend
      - frontend
    
    tty: true

  vote:
    build:
      context: ./vote
    ports:
      - "5000:5000"
    networks:
      - frontend
    depends_on:
      - db


  result:
    build:
      context: ./result
    ports:
      - "4000:4000"
    networks:
      - frontend


  worker:
    build:
      context: ./worker
    networks:
      - backend
      - frontend
    depends_on:
      - redis
      - db


networks:
  frontend:
  backend:

volumes:
  votes: